# Generated by Django 4.2.6 on 2023-12-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
